#!/usr/bin/env python3
"""
Direct comparison of CSS files generated by different layouts
"""
from ePy_docs.writers import DocumentWriter
import pandas as pd
import os

def compare_layout_css():
    print("\n=== EVIDENCIA DIRECTA DE DIFERENCIAS EN LAYOUTS ===\n")
    
    layouts = ['professional', 'creative', 'minimal', 'handwritten']
    css_results = {}
    
    for layout in layouts:
        print(f"--- Generando documento con layout {layout} ---")
        
        # Create writer with specific layout
        writer = DocumentWriter(layout_style=layout)
        
        # Add content
        writer.add_h1(f"Prueba {layout}")
        writer.add_text("Texto de ejemplo para ver diferencias")
        
        df = pd.DataFrame({'Col1': ['A', 'B'], 'Col2': ['X', 'Y']})
        writer.add_table(df, title="Tabla de ejemplo")
        
        # Generate 
        result = writer.generate(output_filename=f"prueba_{layout}", html=True, qmd=False, pdf=False)
        
        if 'html' in result:
            # Read the CSS file that was generated
            css_path = os.path.join(os.path.dirname(result['html']), 'styles.css')
            
            if os.path.exists(css_path):
                with open(css_path, 'r', encoding='utf-8') as f:
                    css_content = f.read()
                
                # Extract key color variables
                import re
                primary_match = re.search(r'--primary-color:\s*([^;]+);', css_content)
                bg_match = re.search(r'--background-color:\s*([^;]+);', css_content) 
                font_match = re.search(r'font-family:\s*([^;]+);', css_content)
                
                css_results[layout] = {
                    'primary_color': primary_match.group(1) if primary_match else 'No encontrado',
                    'background_color': bg_match.group(1) if bg_match else 'No encontrado', 
                    'font_family': font_match.group(1) if font_match else 'No encontrado'
                }
                
                print(f"   Archivo CSS: {css_path}")
                print(f"   Color primario: {css_results[layout]['primary_color']}")
                print(f"   Color fondo: {css_results[layout]['background_color']}")
                print(f"   Fuente: {css_results[layout]['font_family']}")
                print()
            else:
                print(f"   ERROR: No se encontro CSS en {css_path}")
    
    # Compare results
    print("=== COMPARACION DIRECTA ===")
    print("Layout\t\t\tColor Primario\t\t\tColor Fondo\t\t\tFuente")
    print("-" * 100)
    
    for layout in layouts:
        if layout in css_results:
            data = css_results[layout]
            print(f"{layout:<15}\t{data['primary_color']:<20}\t{data['background_color']:<20}\t{data['font_family']}")
    
    # Check if they're all different
    primary_colors = [css_results[layout]['primary_color'] for layout in layouts if layout in css_results]
    bg_colors = [css_results[layout]['background_color'] for layout in layouts if layout in css_results]
    fonts = [css_results[layout]['font_family'] for layout in layouts if layout in css_results]
    
    print(f"\nRESULTADO:")
    print(f"- Colores primarios únicos: {len(set(primary_colors))} de {len(primary_colors)}")
    print(f"- Colores de fondo únicos: {len(set(bg_colors))} de {len(bg_colors)}")  
    print(f"- Fuentes únicas: {len(set(fonts))} de {len(fonts)}")
    
    if len(set(primary_colors)) > 1:
        print("\n✅ CONFIRMADO: Los layouts SI generan colores diferentes")
    else:
        print("\n❌ PROBLEMA: Todos los layouts generan el mismo color")

if __name__ == "__main__":
    compare_layout_css()